### ISSUE TITLE
rgeos requires extra libraries on linux, can we make it suggests rather than imports

### ISSUE THREAD

**Issue by andrewdolman** [EarthSystemDiagnostics/ecustools#9]
Package rgeos, used only by ggpolar, requires libgeos++-dev to install on linux. This is tricky when using hosted Rstudio for example. Can we make rgeos a "suggests" rather than "imports" and trigger a warning on first use of ggpolar?

**Comment by thomas-muench** [comment]
You are correct in that the rgeos package is only needed for the ggpolar function (besides being a suggest dependency of the raster package), and there only in case "invalid geometries" need to be fixed. Without this, ggpolar would exit with an error in this case.

-----------------------------------------------------------------------------------------------------------------------------
[mostly for documentation purposes]:
This invalid geometry error seems only to occur for plotting segments in the Northern Hemisphere and must have something to do with clipping of the landmask polygons, which causes trouble in some deeply nested function. Here is a sample error output:
```R
Error in RGEOSBinTopoFunc(spgeom1, spgeom2, byid, id, drop_lower_td, unaryUnion_if_byid_false,  : 
  TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -95.902496339999999 66.946641920000005 at -95.902496339999999 66.946641920000005
In addition: Warning messages:
1: In RGEOSUnaryPredFunc(spgeom, byid, "rgeos_isvalid") :
  Ring Self-intersection at or near point -95.902496339999999 66.946641920000005
2: In rgeos::gIntersection(x[i, ], y, byid = TRUE, drop_lower_td = TRUE) :
  Invalid objects found; consider using set_RGEOS_CheckValidity(2L)
```
This error can indeed be fixed by following the suggestion from 2. above (setting `rgeos::set_RGEOS_CheckValidity(2L)`), which fixes the invalid geometry by "zero-width buffering" and only issues a warning. However, for this one obviously needs the rgeos package installed.

This problem seems pretty much undocumented online, at least concerning R; the only reference I found was here: https://gis.stackexchange.com/questions/379693/crop-wrld-simpl-gives-error-after-r-update.

-----------------------------------------------------------------------------------------------------------------------------
Suggested solution:

Since this invalid geometry issue seems to be an edge case, I agree with that the rgeos package needs only be a suggested dependency. But we should inform users who don't have rgeos installed, that in case of errors with ggpolar they should consider installing rgeos in order to try to fix it:

```R
# force to repair invalid geometries if rgeos is available
if (requireNamespace("rgeos", quietly = TRUE)) {
  rgeos::set_RGEOS_CheckValidity(2L)
} else {
  message("Package 'rgeos' not installed on your system. When encountering an error with ggpolar() 
           from invalid geometry with Ring Self-intersection, please install 'rgeos' to fix it.")
}
```

Would you agree with this approach, @andrewdolman?

I would also keep this approach when eventually doing the suggested splitting up of ecustools into several smaller packages.

This approch would issue the message each time ggpolar is run - do you know how to issue the warning only once per session, @andrewdolman?

**Comment by andrewdolman** [comment]
Yes, I like this approach. For now let's just take the simplest option of warning each time the function is used.
